apiVersion : apps/v1
kind : Deployment
metadata:
  name : yooga-deployment
  labels:
    app : httpd
spec:
  template:
    metadata:
      labels:
        app : httpd
    spec:
      containers:
        - name : yooga
          image: devtechieops/yooga:1.0
          ports:
            - containerPort : 80
  selector:
    matchLabels:
      app : httpd
